import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import  output  from "../../public/output.png";
const inter = Inter({ subsets: ["latin"] });
import {NextUIProvider} from "@nextui-org/react";
import toast, { Toaster } from 'react-hot-toast';
import {Providers} from "./providers";
import NextTopLoader from 'nextjs-toploader';
import { ApolloProvider,ApolloClient,InMemoryCache } from "@apollo/client";
import Footer from "./components/Footer";
import { AuthProvider } from "./providers2";
const cache=new InMemoryCache()
const client= new ApolloClient({
  cache,
  uri:"http://localhost:4444/graphql/"

})
export const metadata: Metadata = {
  title: "Your Personal Diagnostic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
      <body style={{
        backgroundColor:"#FBF3FD",}}  className={inter.className}>
          <Providers>
          <Toaster
  position="top-center"
  reverseOrder={false}
  gutter={8}
  containerClassName=""
  containerStyle={{}} 
  toastOptions={{
    // Define default options
    className: '',
    duration: 5000,
    style: {
      background: '#363636',
      color: '#fff',
    },
    
    // Default options for specific types
    success: {
      duration: 3000,
      theme: {
        primary: 'green',
        secondary: 'black',
      },
    },
  }}
/>

<NextTopLoader
      color="#5D49EC"
      initialPosition={0.08}
      crawlSpeed={100}
      height={2}
      crawl={true}
      showSpinner={false}
      easing="ease"
      speed={100}
      shadow="0 0 10px #2299DD,0 0 5px #2299DD"
      template='<div class="bar" role="bar"><div class="peg"></div></div> 
      <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
      zIndex={1600}
      showAtBottom={false} />
       <div className="ball  left-[30vw] bottom-7"></div>
        <div className="ball  -top-36 left-[30vw]"></div>
        <div className="ball  left-[66vw] "></div>
        <div className="ball  left-[66vw] top-[160vh] "></div>
        <AuthProvider>
        <Navbar>
        </Navbar>
        {children}
      <Footer></Footer>
        </AuthProvider>
          </Providers>
        </body>
    </html>
 
  );
}
