import React from 'react'

export const TermsConditions = () => {
  return (
    <div className=''>
        <h1 className='text-2xl font-bold'>

        Terms and Conditions
        </h1>
        <p>This tool is designed solely for testing purposes and is intended to assist in the detection of pneumonia and brain tumors using machine learning algorithms. Please note that all accuracies and results generated by this tool may be subject to defects and inaccuracies. The tool is not intended to be used as a substitute for professional medical advice, diagnosis, or treatment. Users should not rely on the results provided by this tool to make any healthcare decisions or to assess the health condition of any individual. We strongly recommend consulting with a qualified healthcare provider for any medical concerns or questions. By using this tool, you acknowledge and agree that the developers and providers of this tool are not liable for any errors, inaccuracies, or any actions taken based on the results generated by this tool. Use of this tool is at your own risk.</p>
    
    </div>
  )
}
